//
//  FlagsOfCountries.swift
//  CountriesQuiz
//
//  Created by Marat Shagiakhmetov on 01.12.2022.
//

import Foundation

class FlagsOfCountries {
    static let shared = FlagsOfCountries()
    
    let images = ["australia", "austria", "azerbaijan", "aland islands", "albania",
    "algeria", "american samoa", "anguilla", "angola", "andorra", "antarctica",
    "antigua and barbuda", "argentina", "armenia", "aruba", "british isles",
    "afghanistan", "bahamas", "bangladesh", "barbados", "bahrain", "belarus",
    "belize", "belgium", "benin", "bermuda", "bulgaria", "bolivia", "bonaire",
    "bosnia and herzegovina", "bostwana", "brazil", "brunei", "burkina-faso",
    "burundi", "bhutan", "vanuatu", "vatican city", "great britain", "hungary",
    "venezuela", "british virgin islands", "united states virgin islands",
    "east timor", "vietnam", "gabon", "haiti", "guyana", "gambia", "ghana",
    "guadepoule", "guatemala", "guinea", "guinea-bissau", "germany", "guernsey",
    "gibraltar", "honduras", "hong kong", "grenada", "greenland", "greece",
    "georgia", "guam", "denmark", "jersey", "djibouti", "dominica",
    "dominican republic", "egypt", "zambia", "western sahara", "zimbabwe",
    "israel", "india", "indonesia", "jordan", "iraq", "iran", "ireland", "iceland",
    "spain", "italy", "yemen", "cabo-verde", "kazakhstan", "cambodia", "cameroon",
    "canada", "qatar", "kenya", "cyprus", "kyrgyzstan", "kiribati", "china",
    "north korea", "cocos islands", "colombia", "comoros", "republic congo",
    "democratic republic of the congo", "kosovo", "costa rica", "ivory coast",
    "cuba", "kuwait", "curacao", "laos", "latvian", "lesotho", "liberia", "lebanon",
    "libya", "lithuania", "liechtenstein", "luxembourg", "mauritius", "mauritania",
    "madagascar", "mayotte", "makau", "malawi", "malaysia", "mali", "maldives",
    "malta", "morocco", "martinique", "marshall islands", "mexico", "micronesia",
    "mozambique", "moldova", "monaco", "mongolia", "montserrat", "myanmar",
    "namibia", "nauru", "nepal", "niger", "nigeria", "netherlands", "nicaragua",
    "niue", "new zealand", "new caledonia", "norway", "isle of man", "norfolk island",
    "christmas islands", "saint helena islands", "pitcairn islands",
    "turks and caicos islands", "uae", "oman", "cayman islands", "cook islands",
    "pakistan", "palau", "palestine", "panama", "papua new guinea", "paraguay",
    "peru", "poland", "portugal", "puerto rico", "south korea", "reunion",
    "russia", "rwanda", "romania", "el salvador", "samoa", "san marino",
    "sao tome and principe", "saudi arabia", "northern macedonia",
    "northern mariana islands", "seychelles islands", "saint-barthelemy",
    "saint-pierre and miquelon", "senegal", "saint vincent and grenadines",
    "saint kitts and nevis", "saint lucia", "serbia", "singapore", "sint maarten",
    "syria", "slovakia", "slovenia", "usa", "solomon islands", "somalia",
    "sudan", "suriname", "sierra leone", "tajikistan", "thailand", "taiwan",
    "tanzania", "togo", "tokelau", "tonga", "trinidad and tobago", "tuvalu",
    "tunisia", "turkmenistan", "turkey", "uganda", "uzbekistan", "ukraine",
    "wallis and futuna", "uruguay", "faroe islands", "fiji", "philippines",
    "finland", "falkland islands", "france", "french guiana", "french polynesia",
    "eparse islands", "croatia", "central african republic", "chad", "montenegro",
    "czech", "chile", "switzerland", "sweden", "sri lanka", "ecuador",
    "equatorial guinea", "eritrea", "eswatini", "estonia", "ethiopia",
    "south georgia and south sandwich", "south africa", "south sudan", "jamaica",
    "japan"]
    
    let countries = ["Австралия", "Австрия", "Азербайджан", "Аландские острова",
    "Албания", "Алжир", "Американское Самоа", "Ангилья", "Ангола", "Андорра",
    "Антарктида", "Антигуа и Барбуда", "Аргентина", "Армения", "Аруба",
    "Британские острова", "Афганистан", "Багамские острова", "Бангладеш",
    "Барбадос", "Бахрейн", "Беларусь", "Белиз", "Бельгия", "Бенин",
    "Бермудские острова", "Болгария", "Боливия", "Бонайре", "Босния и Герцеговина",
    "Ботсвана", "Бразилия", "Бруней", "Буркина-Фасо", "Бурунди", "Бутан",
    "Вануату", "Ватикан", "Великобритания", "Венгрия", "Венесуэла",
    "Британские Виргинские острова", "Американские Виргинские острова",
    "Восточный Тимор", "Вьетнам", "Габон", "Гаити", "Гайана", "Гамбия", "Гана",
    "Гваделупа", "Гватемала", "Гвинея", "Гвинея-Бисау", "Германия", "Гернси",
    "Гибралтар", "Гондурас", "Гонконг", "Гренада", "Гренландия", "Греция",
    "Грузия", "Гуам", "Дания", "Джерси", "Джибути", "Доминика",
    "Доминиканская республика", "Египет", "Замбия", "Западная Сахара",
    "Зимбабве", "Израиль", "Индия", "Индонезия", "Иордания", "Ирак", "Иран",
    "Ирландия", "Исландия", "Испания", "Италия", "Йемен", "Кабо-Верде",
    "Казахстан", "Камбоджа", "Камерун", "Канада", "Катар", "Кения", "Кипр",
    "Кыргызстан", "Кирибати", "Китай", "КНДР", "Кокосовые острова", "Колумбия",
    "Коморские острова", "Республика Конго", "Демократическая Республика Конго",
    "Республика Косово", "Коста-Рика", "Кот-д'Ивуар", "Куба", "Кувейт", "Кюрасао", 
    "Лаос", "Латвия", "Лесото", "Либерия", "Ливан", "Ливия", "Литва", "Лихтенштейн",
    "Люксембург", "Маврикий", "Мавритания", "Мадагаскар", "Майотта", "Макао",
    "Малави", "Малайзия", "Мали", "Мальдивские острова", "Мальта", "Марокко",
    "Мартиника", "Маршалловы острова", "Мексика", "Микронезия", "Мозамбик",
    "Молдова", "Монако", "Монголия", "Монтсеррат", "Мьянма", "Намибия", "Науру",
    "Непал", "Нигер", "Нигерия", "Нидерланды", "Никарагуа", "Ниуэ",
    "Новая Зеландия", "Новая Каледония", "Норвегия", "Остров Мэн", "Остров Норфолк",
    "Остров Роджества", "Острова Святой Елены", "Острова Питкэрн",
    "Острова Теркс и Кайкос", "ОАЭ", "Оман", "Каймановы острова", "Острова Кука",
    "Пакистан", "Палау", "Палестина", "Панама", "Папуа - Новая Гвинея", "Парагвай",
    "Перу", "Польша", "Португалия", "Пуэрто-Рико", "Южная Корея", "Реюньон",
    "Россия", "Руанда", "Румыния", "Сальвадор", "Самоа", "Сан-Марино",
    "Сан-Томе и Принсипи", "Саудовская Аравия", "Северная Македония",
    "Северные Марианские острова", "Сейшельские острова", "Сен-Бартелеми",
    "Сен-Пьер и Микелон", "Сенегал", "Сент-Винсент и Гренадины",
    "Сент-Китс и Невис", "Сент-Люсия", "Сербия", "Сингапур", "Синт-Мартен",
    "Сирия", "Словакия", "Словения", "США", "Соломоновы острова", "Сомали",
    "Судан", "Суринам", "Сьерра-Леоне", "Таджикистан", "Таиланд", "Тайвань",
    "Танзания", "Того", "Токелау", "Тонга", "Тринидад и Тобаго", "Тувалу", "Тунис",
    "Туркменистан", "Турция", "Уганда", "Узбекистан", "Украина", "Уоллис и Футуна",
    "Уругвай", "Фарерские острова", "Фиджи", "Филиппины", "Финляндия",
    "Фолклендские острова", "Франция", "Французская Гвиана", "Французская Полинезия",
    "Острова Эпарс", "Хорватия", "Центральноафриканская Республика",
    "Чад", "Черногория", "Чехия", "Чили", "Швейцария", "Швеция", "Шри-Ланка",
    "Эквадор", "Экваториальная Гвинея", "Эритрея", "Эсватини", "Эстония",
    "Эфиопия", "Южная Георгия и Южные Сандвичевы", "ЮАР", "Южный Судан", "Ямайка",
    "Япония"]
    
    let capitals = ["Канберра", "Вена", "Баку", "Мариехамн", "Тирана", "Алжир",
    "Паго-Паго", "Валли", "Луанда", "Андорра-ла-Велья", "Мак-Мердо", "Сент-Джонс",
    "Буэнос-Айрес", "Ереван", "Ораньестад", "?", "Кабул", "Нассау", "Дакка",
    "Бриджтаун", "Манама", "Минск", "Бельмопан", "Брюссель", "Порто-Ново", "Гамильтон",
    "София", "Сукре / Ла-Пас", "Кралендейк", "Сараево", "Габороне", "Бразилиа",
    "Бандар-Сери-Бегаван", "Уагадугу", "Гитега", "Тхимпху", "Порт-Вила", "Ватикан",
    "Лондон", "Будапешт", "Каракас", "Род-Таун", "Шарлотта-Амалия", "Дили", "Ханой",
    "Либревиль", "Порт-о-Пренс", "Джорджтаун", "Банжул", "Аккра", "Бас-Тер", "Гватемала",
    "Конакри", "Бисау", "Берлин", "Сент-Питер-Порт", "Гибралтар", "Тегусигальпа",
    "Гонконг", "Сент-Джорджес", "Нуук / Готхоб", "Афины", "Тбилиси", "Хаганта",
    "Копенгаген", "Сент-Хелиер", "Джибути", "Розо", "Санто-Доминго", "Каир", "Лусака",
    "Тифарити", "Хараре", "Иерусалим", "Нью-Дели", "Джакарта", "Амман", "Багдад",
    "Тегеран", "Дублин", "Рейкьявик", "Мадрид", "Рим", "Сана", "Прая", "Астана",
    "Камбоджа", "Яунде", "Оттава", "Доха", "Найроби", "Никосия", "Бишкек", "Южная Тарава",
    "Пекин", "Пхеньян", "Бантам", "Богота", "Морони", "Браззавиль", "Киншаса",
    "Приштина", "Сан-Хосе", "Ямусукро", "Гавана", "Эль-Кувейт", "Виллемстад",
    "Вьентьян", "Рига", "Масеру", "Монровия", "Бейрут", "Триполи", "Вильнюс",
    "Вадуц", "Люксембург", "Маврикий", "Нуакшот", "Антананариву", "Мамудзу",
    "Макао", "Лилонгве", "Куала-Лумпур", "Бамако", "Мале", "Валлетта", "Рабат",
    "Фор-де-Франс", "Маджуро", "Мехико", "Паликир", "Мапуту", "Кишинев", "Монако",
    "Улан-Батор", "Плимут / Брейдс", "Нейпьидо", "Виндхук", "Ярен", "Катманду",
    "Ниамей", "Абуджа", "Амстердам", "Манагуа", "Алофи", "Уэллингтон", "Нумеа",
    "Осло", "Дуглас", "Кингстон / Бернт-Пайн", "Флайинг-Фиш-Ков", "Джеймстаун",
    "Адамстаун", "Коберн-Таун", "Абу-Даби", "Маскат", "Джорджтаун", "Аваруа",
    "Исламабад", "Нгерулмуд", "Восточный Иерусалим", "Панама", "Порт-Морсби",
    "Асунсьон", "Лима", "Варшава", "Лиссабон", "Сан-Хуан", "Сеул", "Сен-Дени",
    "Москва", "Кигали", "Бухарест", "Сан-Сальвадор", "Апиа", "Сан-Марино",
    "Сан-Томе", "Эр-Рияд", "Скопье", "Сайпан", "Виктория", "Густавия", "Сен-Пьер",
    "Дакар", "Кингстаун", "Бастер", "Кастри", "Белград", "Сингапур", "Филипсбург",
    "Дамаск", "Братислава", "Любляна", "Вашингтон", "Хониара", "Могадишо", "Хартум",
    "Парамарибо", "Фритаун", "Душанбе", "Бангкок", "Тайбэй", "Додома / Дар-эс-Салам",
    "Ломе", "Атафу", "Нукуалофа", "Порт-оф-Спейн", "Фунафути", "Тунис", "Ашхабад",
    "Анкара", "Кампала", "Ташкент", "Киев", "Мата-Уту", "Монтевидео", "Торсхавн",
    "Сува", "Манила", "Хельсинки", "Стэнли", "Париж", "Кайенна", "Папаэте", "Европа",
    "Загреб", "Банги", "Наджамена", "Подгорица / Цетине", "Прага", "Сантьяго",
    "Берн", "Стокгольм", "Котте", "Кито", "Малабо", "Асмэра", "Мбабане", "Таллин",
    "Аддис-Абеба", "Кинг-Эдуард-Пойнт", "Претория / Кейптаун", "Джуба", "Кингстон",
    "Токио"]
    
    let imagesOfAmericanContinent = ["canada", "usa", "mexico", "bermuda",
    "greenland", "saint-pierre and miquelon", "belize", "guatemala", "honduras",
    "costa rica", "nicaragua", "panama", "el salvador", "antigua and barbuda",
    "bahamas", "barbados", "haiti", "grenada", "dominica", "dominican republic",
    "cuba", "saint vincent and grenadines", "saint kitts and nevis", "saint lucia",
    "trinidad and tobago", "jamaica", "united states virgin islands", "anguilla",
    "aruba", "bonaire", "british virgin islands", "guadepoule", "cayman islands",
    "curacao", "martinique", "montserrat", "puerto rico", "saint-barthelemy",
    "sint maarten", "turks and caicos islands", "argentina", "bolivia", "brazil",
    "venezuela", "guyana", "colombia", "paraguay", "peru", "suriname", "uruguay",
    "chile", "ecuador", "falkland islands", "south georgia and south sandwich",
    "french guiana"]
    
    let countriesOfAmericanContinent = ["Канада", "США", "Мексика",
    "Бермудские острова", "Гренландия", "Сен-Пьер и Микелон", "Белиз", "Гватемала",
    "Гондурас", "Коста-Рика", "Никарагуа", "Панама", "Сальвадор", "Антигуа и Барбуда",
    "Багамские острова", "Барбадос", "Гаити", "Гренада", "Доминика",
    "Доминиканская республика", "Куба", "Сент-Винсент и Гренадины",
    "Сент-Китс и Невис", "Сент-Люсия", "Тринидад и Тобаго", "Ямайка",
    "Американские Виргинские острова", "Ангилья", "Аруба", "Бонайре",
    "Британские Виргинские острова", "Гвадепула", "Каймановы острова", "Кюрасао",
    "Мартиника", "Монтсеррат", "Пуэрто-Рико", "Сен-Бартелеми", "Синт-Мартен",
    "Острова Теркс и Кайкос", "Аргентина", "Боливия", "Бразилия", "Венесуэла",
    "Гайана", "Колумбия", "Парагвай", "Перу", "Суринам", "Уругвай", "Чили",
    "Эквадор", "Фолклендские острова", "Южная Георгия и Южные Сандвичевы",
    "Французская Гвиана"]
    
    let capitalsOfAmericaContinent = ["Канберра", "Вашингтон", "Мехико", "Гамильтон",
    "Нуук / Готхоб", "Сен-Пьер", "Бельмопан", "Гватемала", "Тегусигальпа", "Сан-Хосе",
    "Манагуа", "Панама", "Сан-Сальвадор", "Сент-Джонс", "Нассау", "Бриджтаун",
    "Порт-о-Пренс", "Сент-Джорджес", "Розо", "Санто-Доминго", "Гавана", "Кингстаун",
    "Бастер", "Кастри", "Порт-оф-Спейн", "Кингстон", "Шарлотта-Амалия", "Валли",
    "Ораньестад", "Кралендейк", "Род-Таун", "Бас-Тер", "Джорджтаун", "Виллемстад",
    "Фор-де-Франс", "Плимут / Брейдс", "Сан-Хуан", "Густавия", "Филипсбург",
    "Коберн-Таун", "Буэнос-Айрес", "Сукре / Ла-Пас", "Бразилиа", "Каракас",
    "Джорджтаун", "Богота", "Асунсьон", "Лима", "Парамарибо", "Монтевидео", 
    "Сантьяго", "Кито", "Стэнли", "Кинг-Эдуард-Пойнт", "Кайенна"]
    
    let imagesOfEuropeanContinent = ["austria", "aland islands", "belgium",
    "great britain", "germany", "guernsey", "gibraltar", "jersey", "ireland",
    "liechtenstein", "luxembourg", "monaco", "netherlands", "isle of man",
    "france", "switzerland", "belarus", "bulgaria", "hungary", "moldova", "poland",
    "russia", "romania", "slovakia", "czech", "ukraine", "denmark", "iceland",
    "latvian", "lithuania", "norway", "finland", "estonia", "sweden", "albania",
    "andorra", "bosnia and herzegovina", "vatican city", "greece", "spain",
    "italy", "kosovo", "northern macedonia", "malta", "portugal", "san marino",
    "serbia", "slovenia", "faroe islands", "croatia", "montenegro"]
    
    let countriesOfEuropeanContinent = ["Австрия", "Аландские острова", "Бельгия",
    "Великобритания", "Германия", "Гернси", "Гибралтар", "Джерси", "Ирландия",
    "Лихтенштейн", "Люксембург", "Монако", "Нидерланды", "Остров Мэн", "Франция",
    "Швейцария", "Беларусь", "Болгария", "Венгрия", "Молдова", "Польша", "Россия",
    "Румыния", "Словакия", "Чехия", "Украина", "Дания", "Исландия", "Латвия",
    "Литва", "Норвегия", "Финляндия", "Эстония", "Швеция", "Албания", "Андорра",
    "Босния и Герцеговина", "Ватикан", "Греция", "Испания", "Италия", "Республика Косово",
    "Северная Македония", "Мальта", "Португалия", "Сан-Марино", "Сербия",
    "Словения", "Фарерские острова", "Хорватия", "Черногория"]
    
    let imagesOfAfricanContinent = ["algeria", "egypt", "western sahara", "libya",
    "morocco", "sudan", "tunisia", "benin", "burkina-faso", "gambia", "ghana",
    "guinea", "guinea-bissau", "cabo-verde", "ivory coast", "liberia", "mauritania",
    "mali", "niger", "nigeria", "senegal", "sierra leone", "togo", "gabon",
    "cameroon", "democratic republic of the congo", "republic congo",
    "sao tome and principe", "central african republic", "chad", "equatorial guinea",
    "burundi", "djibouti", "kenya", "rwanda", "somalia", "tanzania", "uganda",
    "eritrea", "ethiopia", "south sudan", "angola", "bostwana", "zambia",
    "zimbabwe", "comoros", "lesotho", "mauritius", "madagascar", "mayotte",
    "malawi", "mozambique", "namibia", "reunion", "eswatini", "saint helena islands",
    "seychelles islands", "eparse islands", "south africa"]
    
    let countriesOfAfricanContinent = ["Алжир", "Египет", "Западная Сахара",
    "Ливия", "Марокко", "Судан", "Тунис", "Бенин", "Буркина-Фасо", "Гамбия",
    "Гана", "Гвинея", "Гвинея-Бисау", "Кабо-Верде", "Кот-д'Ивуар", "Либерия",
    "Мавритания", "Мали", "Нигер", "Нигерия", "Сенегал", "Сьерра-Леоне",
    "Того", "Габон", "Камерун", "Демократическая Республика Конго",
    "Республика Конго", "Сан-Томе и Принсипи", "Центральноафриканская Республика",
    "Чад", "Экваториальная Гвинея", "Бурунди", "Джибути", "Кения", "Руанда",
    "Сомали", "Танзания", "Уганда", "Эритрея", "Эфиопия", "Южный Судан",
    "Ангола", "Ботсвана", "Замбия", "Зимбабве", "Коморские острова", "Лесото",
    "Маврикий", "Мадагаскар", "Майотта", "Малави", "Мозамбик", "Намибия",
    "Реюньон", "Эсватини", "Острова Святой Елены", "Сейшельские острова",
    "Острова Эпарс", "ЮАР"]
    
    let imagesOfAsianContinent = ["azerbaijan", "armenia", "afghanistan",
    "bangladesh", "bahrain", "british isles", "brunei", "bhutan", "east timor",
    "vietnam", "georgia", "israel", "india", "indonesia", "jordan", "iraq",
    "iran", "yemen", "kazakhstan", "cambodia", "qatar", "cyprus", "kyrgyzstan",
    "china", "hong kong", "makau", "taiwan", "cocos islands", "north korea",
    "south korea", "kuwait", "laos", "lebanon", "malaysia", "maldives",
    "mongolia", "myanmar", "nepal", "uae", "oman", "christmas islands",
    "pakistan", "palestine", "saudi arabia", "singapore", "syria", "tajikistan",
    "thailand", "turkmenistan", "turkey", "uzbekistan", "philippines", "sri lanka",
    "japan"]
    
    let countriesOfAsianContinent = ["Азербайджан", "Армения", "Афганистан",
    "Бангладеш", "Бахрейн", "Британские острова", "Бруней", "Бутан",
    "Восточный Тимор", "Вьетнам", "Грузия", "Израиль", "Индия", "Индонезия",
    "Иордания", "Ирак", "Иран", "Йемен", "Казахстан", "Камбоджа", "Катар",
    "Кипр", "Кыргызстан", "Китай", "Гонконг", "Макао", "Тайвань",
    "Кокосовые острова", "КНДР", "Южная Корея", "Кувейт", "Лаос", "Ливан",
    "Малайзия", "Мальдивские острова", "Монголия", "Мьянма", "Непал", "ОАЭ",
    "Оман", "Остров Роджества", "Пакистан", "Палестина", "Саудовская Аравия",
    "Сингапур", "Сирия", "Таджикистан", "Таиланд", "Туркменистан", "Турция",
    "Узбекистан", "Филиппины", "Шри-Ланка", "Япония"]
    
    let imagesOfOceanContinent = ["australia", "vanuatu", "papua new guinea",
    "solomon islands", "fiji", "kiribati", "marshall islands", "nauru",
    "new zealand", "palau", "samoa", "tonga", "tuvalu", "micronesia",
    "norfolk island", "new caledonia", "guam", "northern mariana islands",
    "american samoa", "niue", "cook islands", "pitcairn islands", "tokelau",
    "wallis and futuna", "french polynesia", "antarctica"]
    
    let countriesOfOceanContinent = ["Австралия", "Вануату",
    "Папуа - Новая Гвинея", "Соломоновы острова", "Фиджи", "Кирибати",
    "Маршалловы острова", "Науру", "Новая Зеландия", "Палау", "Самоа", "Тонга",
    "Тувалу", "Микронезия", "Остров Норфолк", "Новая Каледония", "Гуам",
    "Северные Марианские острова", "Американское Самоа", "Ниуэ", "Острова Кука",
    "Острова Питкэрн", "Токелау", "Уоллис и Футуна", "Французская Полинезия",
    "Антарктида"]
    
    private init() {}
}
